# Generated by Django 3.0.10 on 2021-01-31 22:21

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_auto_20210131_2321"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("open", "open"),
                            ("waiting", "waiting"),
                            ("inactive", "inactive"),
                            ("active", "active"),
                            ("paused", "paused"),
                            ("complete", "complete"),
                        ],
                        default="open",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Task Name")),
                ("info", models.TextField(verbose_name="Information")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="project", unique=True
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.Task"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.Project",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.DeleteModel(name="Tasks"),
    ]
