# Generated by Django 3.0.10 on 2021-01-31 22:51

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tasks", "0003_auto_20210131_2350")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.Task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="project", unique=True
            ),
            preserve_default=False,
        ),
    ]
