# Generated by Django 3.0.10 on 2021-01-31 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20210131_2321"),
        ("tasks", "0004_auto_20210131_2351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.Project",
            ),
            preserve_default=False,
        )
    ]
