# Generated by Django 3.0.10 on 2021-02-01 10:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0005_auto_20210201_0051")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="info",
            field=markdownx.models.MarkdownxField(verbose_name="Information"),
        )
    ]
