# Generated by Django 3.0.10 on 2021-02-01 11:54

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0006_auto_20210201_1147")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="info",
            field=markdownx.models.MarkdownxField(
                verbose_name="Information (Markdown)"
            ),
        )
    ]
