# Generated by Django 3.0.10 on 2021-02-08 16:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tasks", "0008_note")]

    operations = [
        migrations.AddField(
            model_name="note",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="task", unique=True
            ),
            preserve_default=False,
        )
    ]
