# Generated by Django 3.0.10 on 2021-02-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tasks", "0009_note_slug")]

    operations = [migrations.RemoveField(model_name="task", name="parent_task")]
