# Generated by Django 3.0.10 on 2021-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeats',
            field=models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('bi-weekly', 'bi-weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly')], max_length=32, null=True, verbose_name='Repeats'),
        ),
    ]
