version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pdntasks_local_django
    container_name: django_pdntasks
    depends_on:
      - postgres
      - mailhog
      - celerybeat
      - flower
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pdntasks_local_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: pdntasks_local_docs
    container_name: pdntasks_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./pdntasks:/app/pdntasks:z
    ports:
      - "7000:7000"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: pdntasks_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    <<: *django
    image: pdntasks_local_celeryworker
    container_name: pdntasks_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: pdntasks_local_celerybeat
    container_name: pdntasks_local_celerybeat
    depends_on:
      - celeryworker
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: pdntasks_local_flower
    container_name: pdntasks_local_flower
    depends_on:
      - celerybeat
    ports:
      - "5555:5555"
    command: /start-flower
