# Generated by Django 3.0.10 on 2021-07-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(null=True, upload_to='invoices/%Y%m%d_%h%M/', verbose_name='Invoice File'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=1, max_length=16, verbose_name='Invoice Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid Date'),
        ),
    ]
