# Generated by Django 3.0.10 on 2021-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_auto_20210705_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y%m%d_%h%M/', verbose_name='Invoice File'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user'], name='user_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'invoice_date'], name='user_date_invoice_idx'),
        ),
    ]
