# Generated by Django 3.0.10 on 2021-01-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Client Name"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Abbreviation"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("info", models.TextField(verbose_name="Information")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Project Name"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Abbreviation"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("info", models.TextField(verbose_name="Information")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.Client",
                    ),
                ),
            ],
        ),
    ]
