# Generated by Django 3.0.10 on 2021-02-01 10:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [("projects", "0003_auto_20210131_2321")]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="info",
            field=markdownx.models.MarkdownxField(verbose_name="Information"),
        ),
        migrations.AlterField(
            model_name="project",
            name="info",
            field=markdownx.models.MarkdownxField(verbose_name="Information"),
        ),
    ]
