# Generated by Django 3.0.10 on 2021-02-10 08:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [("projects", "0005_auto_20210201_1254")]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="info",
            field=markdownx.models.MarkdownxField(
                blank=True, verbose_name="Information (Markdown)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="info",
            field=markdownx.models.MarkdownxField(
                blank=True, verbose_name="Information (Markdown)"
            ),
        ),
    ]
