# Generated by Django 3.0.10 on 2021-02-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0006_auto_20210210_0911")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="parent_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.Project",
            ),
        )
    ]
